import os

translations = {
    'de': {
        'title': 'Tificat - KI-gestützte Erinnerungen, die Nachrichten für Sie verfassen',
        'og_desc': 'Erleben Sie Erinnerungen, bei denen KI personalisierte Nachrichten für Ihre Aufgaben erstellt und sendet. Ein neuer Weg, um organisiert zu bleiben.',
        'hero_label': '🌟 Ein neues Erinnerungserlebnis',
        'hero_h1': 'Erinnerungen, die <br><span>Nachrichten für Sie</span> erfinden',
        'hero_p': 'Erleben Sie Benachrichtigungen, auf die Sie sich freuen werden. KI erstellt einzigartige, personalisierte Nachrichten.',
        'sec_title': 'Benachrichtigungen, auf die Sie sich freuen',
        'sec_p': 'Entwickelt, um den Kreislauf von ignorierten Alarmen zu durchbrechen. Tificat macht aus langweiligen Erinnerungen ansprechende Aktionen.',
        'feat1_h3': 'KI-erstellte Nachrichten',
        'feat1_pc': 'KI generiert einzigartige Nachrichten, basierend auf dem, was Sie tun müssen, so dass alltägliche Aufgaben sich anfühlen wie ein Gespräch mit einem unterstützenden Freund.',
        'feat1_sp': 'KI generiert einzigartige, unterstützende Nachrichten speziell für Ihre anstehenden Aufgaben.',
        'feat2_h3': 'Smarte Sprach-Erstellung',
        'feat2_pc': 'Sagen Sie einfach "Medizin um 15 Uhr einnehmen". Die KI versteht Ihre Absicht und plant den genauen Zeitplan in Sekunden.',
        'feat2_sp': 'Sprechen Sie Ihre Aufgabe einfach aus. Die KI versteht sie sofort und legt den genauen Zeitplan fest.',
        'feat3_h3': 'Mehrere Persönlichkeiten',
        'feat3_pc': 'Wählen Sie die Ausstrahlung Ihrer KI – von "Ermutigend" und "Humorvoll" bis zu "Butler" oder "Sergeant".',
        'feat3_sp': 'Wählen Sie zwischen verschiedenen KI-Personas wie Butler oder Sergeant, passend zu Ihrer Stimmung.',
        'feat4_h3': 'Zuverlässige Erinnerungen',
        'feat4_pc': 'Verpassen Sie nie wieder etwas Wichtiges. Kombinieren Sie Vorerinnerungen, Nach-Erinnerungen und smarte Schlummerfunktionen.',
        'feat4_sp': 'Smarte Schlummerfunktion und flexible Vor-/Nach-Erinnerungen garantieren, dass Sie nichts Wichtiges verpassen.',
        'ai_header': 'Beispielhafte KI-Nachricht',
        'ai_msg': '💊 Gesundheit ist dein größter Reichtum!<br>Nimm deine Medizin jetzt, dein zukünftiges Ich wird es dir danken!',
        'ai_task': '📝 Aufgabe: Medizin einnehmen',
        'ai_tone': '🎭 Ton: Ermutigend',
        'prem_sub': '<p>Schöpfen Sie die volle Kraft der Positivität aus. Tificat Premium entfernt alle Einschränkungen.</p>',
        'prem_b1': 'Keine Werbung mehr',
        'prem_b2': 'Unbegrenzte geplante Aufgaben erstellen',
        'prem_b3': 'Alle KI-Töne freigeschaltet',
        'prem_b4': 'Flexible Vor- und Nach-Erinnerungs-Einstellungen',
        'cta_h2': '<h2>Bereit für ein neues Erinnerungserlebnis?</h2>',
        'cta_p': 'Erleben Sie Benachrichtigungen, auf die Sie sich tatsächlich freuen werden.',
        'link_terms': 'Nutzungsbedingungen',
        'link_privacy': 'Datenschutzrichtlinie'
    },
    'es': {
        'title': 'Tificat - Recordatorios impulsados por IA que redactan mensajes para ti',
        'og_desc': 'Experimenta recordatorios donde la IA crea y envía mensajes personalizados para tus tareas. Una nueva forma de mantenerte organizado.',
        'hero_label': '🌟 Una nueva experiencia en recordatorios',
        'hero_h1': 'Recordatorios que <br><span>piensan en mensajes</span> para ti',
        'hero_p': 'Experimenta notificaciones que esperarás con ansias. La IA crea mensajes únicos y personalizados adaptados a tus tareas.',
        'sec_title': 'Notificaciones que te alegrará recibir',
        'sec_p': 'Diseñada para romper el ciclo de las alarmas ignoradas. Tificat convierte recordatorios aburridos en acciones entretenidas.',
        'feat1_h3': 'Mensajes creados por IA',
        'feat1_pc': 'La IA genera mensajes únicos basados en lo que necesitas hacer, haciendo que las tareas cotidianas parezcan una conversación con un amigo.',
        'feat1_sp': 'La IA crea mensajes únicos y de apoyo generados específicamente para tus tareas programadas.',
        'feat2_h3': 'Creación por voz inteligente',
        'feat2_pc': 'Simplemente di "Tomar medicina a las 3 PM". La IA entiende tu intención y establece el horario exacto por ti en segundos.',
        'feat2_sp': 'Simplemente di tu tarea en voz alta. La IA la entenderá y establecerá el horario al instante.',
        'feat3_h3': 'Múltiples personalidades',
        'feat3_pc': 'Elige la personalidad de tu IA: desde "Alentador" y "Humorístico" hasta "Mayordomo" o "Sargento".',
        'feat3_sp': 'Elige entre varias personalidades de IA divertidas, como Mayordomo o Sargento, para adaptarlas a tu estado de ánimo.',
        'feat4_h3': 'Recordatorio confiable',
        'feat4_pc': 'Nunca vuelvas a perderte lo importante. Combina pre-recordatorios, post-recordatorios y repeticiones inteligentes para asegurar que cumples.',
        'feat4_sp': 'La repetición inteligente y los pre/post-recordatorios flexibles garantizan que nunca te perderás nada importante.',
        'ai_header': 'Ejemplo de mensaje de IA',
        'ai_msg': '💊 ¡La salud es tu mayor riqueza!<br>Toma tu medicina ahora, ¡tu yo del futuro te lo agradecerá!',
        'ai_task': '📝 Tarea: Tomar medicina',
        'ai_tone': '🎭 Tono: Alentador',
        'prem_sub': '<p>Desbloquea todo el poder de la positividad. Tificat Premium elimina todos los límites.</p>',
        'prem_b1': 'Sin anuncios',
        'prem_b2': 'Crea tareas programadas ilimitadas',
        'prem_b3': 'Todos los tonos de IA desbloqueados',
        'prem_b4': 'Ajustes flexibles de pre y post-recordatorio',
        'cta_h2': '<h2>¿Listo para una nueva experiencia de recordatorio?</h2>',
        'cta_p': 'Experimenta notificaciones que de verdad querrás recibir.',
        'link_terms': 'Términos de servicio',
        'link_privacy': 'Política de privacidad'
    },
    'fr': {
        'title': 'Tificat - Des rappels basés sur l\'IA qui composent des messages pour vous',
        'og_desc': 'Découvrez des rappels où l\'IA crée et envoie des messages personnalisés pour vos tâches. Une nouvelle façon de rester sur la bonne voie.',
        'hero_label': '🌟 Une nouvelle expérience de rappel',
        'hero_h1': 'Des rappels qui <br><span>imaginent des messages</span> pour vous',
        'hero_p': 'Découvrez des notifications que vous aurez hâte de recevoir. L\'IA crée des messages uniques et personnalisés adaptés à vos tâches.',
        'sec_title': 'Des notifications agréables à recevoir',
        'sec_p': 'Conçu pour briser le cycle des alarmes ignorées. Tificat transforme des rappels ennuyeux en actions engageantes.',
        'feat1_h3': 'Messages rédigés par l\'IA',
        'feat1_pc': 'L\'IA génère des messages uniques en fonction de ce que vous avez à faire, donnant l\'impression de converser avec un véritable ami.',
        'feat1_sp': 'L\'IA crée des messages uniques et encourageants pour vos tâches planifiées.',
        'feat2_h3': 'Création vocale intelligente',
        'feat2_pc': 'Dites simplement "Prendre mon médicament à 15 heures". L\'IA comprend votre intention et programme votre agenda en quelques secondes.',
        'feat2_sp': 'Dites simplement votre tâche à haute voix. L\'IA la comprend et règle l\'heure instantanément.',
        'feat3_h3': 'Multiples personnalités',
        'feat3_pc': 'Choisissez l\'ambiance de votre IA : d\'"Encourageant" et "Humoristique" à "Majordome" ou "Sergent".',
        'feat3_sp': 'Choisissez parmi différentes personnalités amusantes pour votre IA, comme le Majordome.',
        'feat4_h3': 'Rappels ultra fiables',
        'feat4_pc': 'Ne ratez plus l\'essentiel. Combinez des pré-rappels, des post-rappels et un mode report intelligent.',
        'feat4_sp': 'Des reports intelligents et des pré/post-rappels flexibles garantissent que vous ne raterez plus rien.',
        'ai_header': 'Exemple de message IA',
        'ai_msg': '💊 La santé est votre plus grande richesse !<br>Prenez votre médicament maintenant, vous vous remercierez plus tard !',
        'ai_task': '📝 Tâche : Prendre médicament',
        'ai_tone': '🎭 Ton : Encourageant',
        'prem_sub': '<p>Libérez le pouvoir de la positivité. Tificat Premium supprime toutes les limites.</p>',
        'prem_b1': 'Suppression des publicités',
        'prem_b2': 'Tâches programmées illimitées',
        'prem_b3': 'Toutes les personnalités de l\'IA débloquées',
        'prem_b4': 'Paramètres de pré et post-rappels avancés',
        'cta_h2': '<h2>Prêt pour une nouvelle expérience ?</h2>',
        'cta_p': 'Découvrez des notifications que vous aurez vraiment hâte de recevoir.',
        'link_terms': 'Conditions d\'utilisation',
        'link_privacy': 'Politique de confidentialité'
    },
    'id': {
        'title': 'Tificat - Pengingat Berbasis AI yang Menulis Pesan untuk Anda',
        'og_desc': 'Rasakan pengalaman pengingat di mana AI menyusun dan mengirimkan pesan untuk setiap tugas Anda. Cara baru agar tidak pernah lupa.',
        'hero_label': '🌟 Pengalaman Pengingat Baru',
        'hero_h1': 'Pengingat yang <br><span>Memikirkan Pesan</span> Untuk Anda',
        'hero_p': 'Nikmati notifikasi yang Anda nantikan. AI akan menyusun pesan unik yang disesuaikan khusus untuk Anda.',
        'sec_title': 'Notifikasi yang Akan Anda Tunggu-tunggu',
        'sec_p': 'Dirancang untuk menghentikan siklus mengabaikan alarm. Tificat mengubah pengingat membosankan menjadi tindakan yang menyenangkan.',
        'feat1_h3': 'Pesan dari AI',
        'feat1_pc': 'AI menghasilkan pesan unik berdasarkan apa yang perlu Anda lakukan, membuat tugas sehari-hari terasa seperti diingatkan oleh sahabat.',
        'feat1_sp': 'AI menyusun pesan motivasi unik khusus untuk tugas terjadwal Anda.',
        'feat2_h3': 'Pembuatan Suara Pintar',
        'feat2_pc': 'Cukup bilang "Minum obat jam 3 sore". AI mengerti maksud Anda dan akan mengatur jadwal tersebut dalam hitungan detik.',
        'feat2_sp': 'Ucapkan saja tugas Anda. AI akan mengerti dan menetapkan jadwal secara instan.',
        'feat3_h3': 'Berbagai Kepribadian',
        'feat3_pc': 'Pilih nuansa AI Anda—dari yang "Memberi Motivasi" dan "Humoris" hingga "Kepala Pelayan" atau "Sersan".',
        'feat3_sp': 'Pilih dari berbagai kepribadian AI yang seru, seperti Kepala Pelayan atau Sersan.',
        'feat4_h3': 'Pengingat yang Andal',
        'feat4_pc': 'Jangan pernah melewatkan hal penting lagi. Gabungkan pengingat awal, pengingat lanjutan, dan fitur snooze pintar.',
        'feat4_sp': 'Fitur snooze pintar dan pengingat awal/lanjutan fleksibel jamin Anda tidak pernah lupa.',
        'ai_header': 'Contoh Pesan AI',
        'ai_msg': '💊 Kesehatan adalah harta terbesarmu!<br>Minum obatmu sekarang juga, dan kesehatanmu esok hari akan berterima kasih!',
        'ai_task': '📝 Tugas: Minum obat',
        'ai_tone': '🎭 Nada: Motivasi',
        'prem_sub': '<p>Buka kekuatan penuh positif. Tificat Premium menghapus semua batasan.</p>',
        'prem_b1': 'Tidak ada iklan',
        'prem_b2': 'Buat jadwal tugas tak terbatas',
        'prem_b3': 'Semua nada AI terbuka',
        'prem_b4': 'Pengaturan pengingat pra & pasca fleksibel',
        'cta_h2': '<h2>Siap untuk Pengalaman Pengingat Baru?</h2>',
        'cta_p': 'Nikmati notifikasi yang sungguh-sungguh Anda nantikan kehadirannya.',
        'link_terms': 'Syarat dan Ketentuan',
        'link_privacy': 'Kebijakan Privasi'
    },
    'ko': {
        'title': 'Tificat - AI가 메시지를 대신 작성해주는 스마트 리마인더',
        'og_desc': 'AI가 당신의 작업을 위해 기발한 메시지를 생각하고 보내주는 리마인더를 경험해보세요. 즐거운 할 일 관리의 새로운 방법입니다.',
        'hero_label': '🌟 새로운 리마인더 경험',
        'hero_h1': 'AI가 메시지를 <br><span>직접 생각해서</span> 보내줍니다',
        'hero_p': '알림이 올 때마다 조금은 설레는 기분. 할 일에 맞춰 AI가 최적의 메시지를 더해 리마인드하는 차세대 앱입니다.',
        'sec_title': '알림이 기다려지는 경험',
        'sec_p': '단순한 알람이 아닌, \'행동하게 만드는\' 기능들을 통해 지루한 리마인더가 즐거운 활력소가 됩니다.',
        'feat1_h3': 'AI가 메시지를 자동 완성',
        'feat1_pc': '할 일의 내용을 바탕으로 AI가 메시지를 생성합니다. 단순한 알림이 나를 응원해주는 말이나, 웃음을 자아내는 메시지로 바뀝니다.',
        'feat1_sp': '등록한 일정에 맞춰 AI가 나를 위한 다정한 메시지를 자동으로 생각하고 보내줍니다.',
        'feat2_h3': '말하기만 하면 바로 등록',
        'feat2_pc': '"오후 3시에 스마트폰 끄기"처럼 소리내어 말하기만 하세요. AI가 내용과 시간을 분석하여 즉시 리마인더를 설정합니다.',
        'feat2_sp': '"오후 3시에 약 먹기"라고 말하기만 하면 끝. AI가 분석하여 즉시 설정해줍니다.',
        'feat3_h3': '다양한 테마와 성격 설정',
        'feat3_pc': '"격려", "유머", "집사", "군대 조교" 등 다양한 페르소나 설정이 가능합니다. 기분에 맞춰 말투를 바꿔보세요.',
        'feat3_sp': '\'집사\'나 \'츤데레\' 등 다양한 AI 톤을 설정 가능. 기분에 맞춰 일상을 즐겁게 만드세요.',
        'feat4_h3': '확실한 리마인드 기능',
        'feat4_pc': '사전/사후 리마인드와 스누즈 기능을 결합하여, "알림은 봤지만 까먹는" 상황을 방지하고 실행을 돕습니다.',
        'feat4_sp': '사전/사후 알림 기능 및 스누즈 설정으로 "나중에 해야지" 하고 잊어버리는 것을 방지합니다.',
        'ai_header': '이렇게 메시지가 도착해요',
        'ai_msg': '💊 건강이야말로 최고의 투자입니다!<br>오늘도 잊지 말고 약을 챙겨드세요, 내일의 당신이 고마워할 거예요!',
        'ai_task': '📝 할 일: 약 챙겨 먹기',
        'ai_tone': '🎭 톤: 다정하게 격려',
        'prem_sub': '<p>Tificat 프리미엄을 통해 제한없이 긍정 에너지를 가득 채워보세요.</p>',
        'prem_b1': '광고 완전 제거',
        'prem_b2': '예약된 작업 무제한 생성 가능',
        'prem_b3': '모든 AI 페르소나 제한 해제',
        'prem_b4': '사전 및 사후 리마인드의 자유로운 설정',
        'cta_h2': '<h2>새로운 리마인더를 경험할 준비가 되셨나요?</h2>',
        'cta_p': '이제 알림이 오는 시간이 즐거워질 것입니다.',
        'link_terms': '이용약관',
        'link_privacy': '개인정보 처리방침'
    },
    'pt-BR': {
        'title': 'Tificat - Lembretes com IA que criam mensagens para você',
        'og_desc': 'Experimente lembretes nos quais a IA elabora e envia mensagens personalizadas para suas tarefas. Uma nova forma de se manter focado.',
        'hero_label': '🌟 Uma Nova Experiência de Lembrete',
        'hero_h1': 'Lembretes que <br><span>pensam em mensagens</span> para você',
        'hero_p': 'Experimente notificações pelas quais você realmente espera. A IA cria mensagens únicas e personalizadas, feitas apenas para você.',
        'sec_title': 'Notificações Que Você Aguarda com Expectativa',
        'sec_p': 'Projetado para quebrar o ciclo de alarmes ignorados. O Tificat transforma lembretes chatos em ações envolventes.',
        'feat1_h3': 'Mensagens Criadas por IA',
        'feat1_pc': 'A IA gera mensagens únicas com base no que você precisa fazer, tornando tarefas rotineiras uma conversa amigável.',
        'feat1_sp': 'A IA elabora mensagens únicas e de apoio para ajudar nas suas tarefas agendadas.',
        'feat2_h3': 'Criação Inteligente por Voz',
        'feat2_pc': 'Basta dizer "Tomar remédio às 15h". A IA entende sua intenção e define a programação exata para você em segundos.',
        'feat2_sp': 'Basta dizer sua tarefa em voz alta. A IA entende instantaneamente e agenda para você.',
        'feat3_h3': 'Várias Personalidades',
        'feat3_pc': 'Escolha a "vibe" da sua IA—de "Encorajadora" e "Bem-humorada" até "Mordomo" ou "Sargento". Ajuste ao seu humor.',
        'feat3_sp': 'Escolha as "vibes" divertidas da sua IA para combinar perfeitamente com seu humor.',
        'feat4_h3': 'Lembrete Confiável',
        'feat4_pc': 'Nunca perca o que é importante. Combine pré-lembretes, pós-lembretes e adiamento inteligente para garantir que fará a tarefa.',
        'feat4_sp': 'A soneca inteligente e lembretes flexíveis garantem que você nunca mais se esquecerá.',
        'ai_header': 'Exemplo de Mensagem IA',
        'ai_msg': '💊 A saúde é o seu maior bem!<br>Tome seu remédio agora, seu "eu" do futuro agradecerá imensamente!',
        'ai_task': '📝 Tarefa: Tomar remédio',
        'ai_tone': '🎭 Tom: Encorajador',
        'prem_sub': '<p>Desbloqueie todo o poder da positividade. Tificat Premium elimina todos os limites.</p>',
        'prem_b1': 'Remover anúncios',
        'prem_b2': 'Crie tarefas agendadas ilimitadas',
        'prem_b3': 'Desbloquear todos os tons da IA',
        'prem_b4': 'Ajustes flexíveis de pré e pós-lembretes',
        'cta_h2': '<h2>Pronto para uma Nova Experiência?</h2>',
        'cta_p': 'Experimente as notificações amigáveis que você adorará receber todos os dias.',
        'link_terms': 'Termos de Serviço',
        'link_privacy': 'Política de Privacidade'
    },
    'pt-PT': {
        'title': 'Tificat - Lembretes Mágicos com IA',
        'og_desc': 'Experimente lembretes onde a IA redige e envia mensagens adaptadas a si. A melhor forma de manter o ritmo.',
        'hero_label': '🌟 A Revolução dos Lembretes',
        'hero_h1': 'Lembretes que <br><span>criam textos incríveis</span> para si',
        'hero_p': 'Encare as notificações com um sorriso. A IA compõe abordagens incrivelmente personalizadas.',
        'sec_title': 'Notificações Que Adorará Receber',
        'sec_p': 'Criado para acabar com as notificações ignoradas. Conclua os seus objetivos sem aquele peso no ombro.',
        'feat1_h3': 'Textos Pensados por IA',
        'feat1_pc': 'A sua agenda diária comentada como se fosse um bom amigo. A IA elabora abordagens originais focadas nos seus objetivos.',
        'feat1_sp': 'A IA constrói mensagens exclusivas e super construtivas para os seus planos.',
        'feat2_h3': 'Voz e Perceção Rápida',
        'feat2_pc': 'Ao verbalizar "Exercício às 9h", o processo termina imediatamente. Não são necessários teclados, tudo é automático.',
        'feat2_sp': 'Adite planos pela voz. A compreensão é instantânea para que ganhe muito mais tempo.',
        'feat3_h3': 'Personalidades Irreverentes',
        'feat3_pc': 'Será motivado por um "Comandante" ou um perspicaz "Mordomo"? Molde a aplicação com base na sua energia da manhã.',
        'feat3_sp': 'Ajuste a personalidade do seu assistente (como Sargento) conforme a sua motivação.',
        'feat4_h3': 'Memória Resiliente',
        'feat4_pc': 'Nunca esqueça tarefas de novo. Beneficie dos alarmes com suspensão seletiva antes e depois do prazo agendado.',
        'feat4_sp': 'Adie com um critério flexível no pré/pós-aviso para uma fiabilidade irrepreensível.',
        'ai_header': 'Exemplo Exclusivo IA',
        'ai_msg': '💊 Manter o corpo no topo de forma exige constância!<br>Não falhe o tempo de medicação e recarregue já a sua energia vital!',
        'ai_task': '📝 Tarefa: Medicação',
        'ai_tone': '🎭 Tom: Motivação Exigente',
        'prem_sub': '<p>Potencie e expanda os benefícios com Tificat Premium.</p>',
        'prem_b1': 'Bloqueio total de anúncios',
        'prem_b2': 'Lembretes simultâneos sem qualquer limite',
        'prem_b3': 'Catálogo total de perfis de inteligência',
        'prem_b4': 'Total ajuste de espaçamento de notificações',
        'cta_h2': '<h2>É Hora de Mudar o Seu Dia?</h2>',
        'cta_p': 'Permita-se conhecer a mais incrível inovação pessoal disponível.',
        'link_terms': 'Termos Gerais',
        'link_privacy': 'Regras de Privacidade'
    },
    'zh-Hans': {
        'title': 'Tificat - 为您代写专属消息的AI提醒应用',
        'og_desc': '体验会替您思考并定制专属提醒文案的全新AI应用，让您再也不会错过任何重要待办。',
        'hero_label': '🌟 开启提醒新体验',
        'hero_h1': '这是会<br><span>替您想好消息</span>的智能提醒',
        'hero_p': '享受每天收到的通知吧！AI 会根据您的具体任务，量身打造独一无二、暖心又有趣的催办消息。',
        'sec_title': '让您心生期待的提醒',
        'sec_p': '打破经常滑掉系统闹钟的坏习惯！Tificat 会让无聊的日程变成令人心情愉悦的小互动。',
        'feat1_h3': 'AI 自动生成专属文案',
        'feat1_pc': '只要设定“喝水”或“交材料”，AI 就会据此生成消息。普通的通知瞬间变成了一句幽默或鼓励的话语，就像有朋友在身边陪伴。',
        'feat1_sp': '只需输入任务，AI即刻为您生成幽默或关怀的专属提醒文案。',
        'feat2_h3': '开口说话就能快速设置',
        'feat2_pc': '只需对着麦克风说“下午3点吃药”，AI能在瞬间解析内容与时间，替您安排妥当——连键盘都不用敲！',
        'feat2_sp': '说出你要做的事！AI语音解析，帮您瞬间设置好精确的提醒日程。',
        'feat3_h3': '多种人设随心切换',
        'feat3_pc': '提供“鼓励”、“幽默”、“管家”、“教官”还有“傲娇”等个性化AI人格。换一种语气，让任务管理不再枯燥！',
        'feat3_sp': '不管是严格教官还是贴心管家，多样AI人设随你心情任意切换。',
        'feat4_h3': '精准不漏的连环提醒',
        'feat4_pc': '支持“事前/事后提醒”与智能全能推迟设置。有效防止“看到了通知却又延后忘了”的尴尬，执行力拉满。',
        'feat4_sp': '事前与事后连环提醒配合智能贪睡，从此拒绝“待会儿再做”。',
        'ai_header': '来看一条AI消息示例',
        'ai_msg': '💊 健康是您最无价的财富投资！<br>为了感谢未来的自己，现在请赶紧把药吃了吧！',
        'ai_task': '📝 待办: 吃药',
        'ai_tone': '🎭 语气: 鼓励表扬',
        'prem_sub': '<p>释放满满的效率与正能量。Tificat Premium 解锁所有功能限制。</p>',
        'prem_b1': '彻底消除所有广告干扰',
        'prem_b2': '待办提醒任务创建无上限',
        'prem_b3': '全套AI人格语气皆可畅享',
        'prem_b4': '灵活自定义事前及事后提醒时长',
        'cta_h2': '<h2>准备好享受全新的提醒了吗？</h2>',
        'cta_p': '即刻体验让您不再感到厌烦、每一次通知都饱含心意的Tificat。',
        'link_terms': '服务条款',
        'link_privacy': '隐私权政策'
    },
    'zh-Hant': {
        'title': 'Tificat - 為您代寫專屬訊息的AI提醒應用',
        'og_desc': '體驗會替您思考並量身打造專屬提醒文案的全新AI應用，讓您再也不會錯過任何重要待辦。',
        'hero_label': '🌟 開啟提醒新體驗',
        'hero_h1': '這是一款會<br><span>替您想好訊息</span>的智慧提醒',
        'hero_p': '享受每天收到的通知吧！AI 會根據您的具體任務，量身打造獨一無二、暖心又有趣的催辦訊息。',
        'sec_title': '讓您心生期待的提醒',
        'sec_p': '打破經常滑掉系統鬧鐘的壞習慣！Tificat 會讓無聊的日程變成令人心情愉悅的小互動。',
        'feat1_h3': 'AI 自動生成專屬文案',
        'feat1_pc': '只要設定「喝水」或「交報告」，AI 就會據此生成訊息。普通的通知瞬間變成了一句幽默或鼓勵的話語，像有朋友在陪伴。',
        'feat1_sp': '只需輸入任務，AI 即刻為您生成幽默或關懷的專屬提醒文案。',
        'feat2_h3': '開口說話就能快速設置',
        'feat2_pc': '只需對著麥克風說「下午3點吃藥」，AI能在瞬間解析內容與時間，替您安排妥當——連鍵盤都不用敲！',
        'feat2_sp': '說出你要做的事！AI語音解析，幫您瞬間設置好精確的提醒日程。',
        'feat3_h3': '多種人設隨心切換',
        'feat3_pc': '提供「鼓勵」、「幽默」、「管家」、「教官」還有「傲嬌」等個性化AI人格。換一種語氣，讓任務管理不再枯燥！',
        'feat3_sp': '不管是嚴格教官還是貼心管家，多樣AI人設隨你心情任意切換。',
        'feat4_h3': '精準不漏的連環提醒',
        'feat4_pc': '支援「事前/事後提醒」與智慧貪睡設置。有效防止「看到了通知卻又延後忘了」的尷尬，執行力拉滿。',
        'feat4_sp': '事前與事後連環提醒配合智慧貪睡，從此拒絕「等一下再做」。',
        'ai_header': '來看一條AI訊息範例',
        'ai_msg': '💊 健康是您最無價的財富投資！<br>為了感謝未來的自己，現在請趕緊把藥吃了吧！',
        'ai_task': '📝 待辦: 吃藥',
        'ai_tone': '🎭 語氣: 鼓勵',
        'prem_sub': '<p>釋放滿滿的效率與質感。Tificat Premium 解鎖所有功能限制。</p>',
        'prem_b1': '徹底消除所有廣告干擾',
        'prem_b2': '待辦提醒任務創建無上限',
        'prem_b3': '全套AI人格語氣皆可暢享',
        'prem_b4': '靈活自定義事前及事後提醒時長',
        'cta_h2': '<h2>準備好享受全新的提醒了嗎？</h2>',
        'cta_p': '體驗讓您不再感到厭煩、每一次通知都飽含心意的Tificat。',
        'link_terms': '服務條款',
        'link_privacy': '隱私權政策'
    }
}

import codecs

with codecs.open('en/landing_page_en.html', 'r', 'utf-8') as f:
    template = f.read()

replacements = [
    ('Tificat - AI-Powered Reminders That Compose Messages for You', 'title'),
    ('Experience reminders where AI crafts and sends personalized messages for your tasks. A new way to stay on track with messages designed just for you.', 'og_desc'),
    ('🌟 A New Reminder Experience', 'hero_label'),
    ('<h1>Reminders That <br><span>Think of Messages</span> For You</h1>', 'hero_h1'),
    ('Experience notifications you\'ll look forward to. AI crafts unique, personalized messages tailored to your tasks to keep you on track.', 'hero_p'),
    ('<h2>Notifications You’ll Look Forward To</h2>', 'sec_title'),
    ('<p>Designed to break the cycle of ignored alarms. Tificat turns boring reminders into engaging actions.</p>', 'sec_p'),
    ('<h3>AI-Crafted Messages</h3>', 'feat1_h3'),
    ('<p class="feature-desc-pc">AI generates unique messages based on what you need to do, making mundane tasks feel like a conversation with a supportive friend.</p>', 'feat1_pc'),
    ('<p class="feature-desc-sp">AI crafts unique, supportive messages specifically generated for your scheduled tasks.</p>', 'feat1_sp'),
    ('<h3>Smart Voice Creation</h3>', 'feat2_h3'),
    ('<p class="feature-desc-pc">Simply say "Take medicine at 3 PM". AI understands your intent and sets the exact schedule for you in seconds—no typing needed.</p>', 'feat2_pc'),
    ('<p class="feature-desc-sp">Just speak your task aloud. AI instantly understands and sets the exact schedule for you.</p>', 'feat2_sp'),
    ('<h3>Multiple Personalities</h3>', 'feat3_h3'),
    ('<p class="feature-desc-pc">Choose your AI\'s vibe—from "Encouraging" and "Humorous" to "Butler" or "Sergeant". Match your reminders to your mood to build lasting habits.</p>', 'feat3_pc'),
    ('<p class="feature-desc-sp">Choose from various fun AI personas, like Butler or Sergeant, to match your current mood.</p>', 'feat3_sp'),
    ('<h3>Reliable Reminding</h3>', 'feat4_h3'),
    ('<p class="feature-desc-pc">Never miss what matters again. Combine pre-reminders, post-reminders, and smart snoozing to ensure you actually follow through.</p>', 'feat4_pc'),
    ('<p class="feature-desc-sp">Smart snoozing and flexible pre/post-reminders guarantee you\'ll never miss what matters.</p>', 'feat4_sp'),
    ('<h3>Example AI Message</h3>', 'ai_header'),
    ('💊 Health is your greatest wealth!<br>Take your medicine now, and your future self will thank you!', 'ai_msg'),
    ('📝 Task: Take medicine', 'ai_task'),
    ('🎭 Tone: Encouraging', 'ai_tone'),
    ('<p>Unlock the full power of positivity. Tificat Premium removes all limits.</p>', 'prem_sub'),
    ('No more advertisements', 'prem_b1'),
    ('Create unlimited scheduled tasks', 'prem_b2'),
    ('All AI tones unlocked', 'prem_b3'),
    ('Flexible pre & post-reminder settings', 'prem_b4'),
    ('<h2>Ready for a New Reminder Experience?</h2>', 'cta_h2'),
    ('Experience notifications you\'ll actually look forward to receiving.', 'cta_p'),
    ('Terms of Service', 'link_terms'),
    ('Privacy Policy', 'link_privacy'),
]

for lang, data in translations.items():
    html_out = template
    html_out = html_out.replace('lang="en"', f'lang="{lang}"')
    
    for en_text, key in replacements:
        if key in data and en_text in html_out:
            html_out = html_out.replace(en_text, data[key])
            
    html_out = html_out.replace('../images/screen_shots/en/', f'../images/screen_shots/{lang}/')
    html_out = html_out.replace('data-lang="en"', f'data-lang="{lang}"')
    
    safe_lang = lang.replace("-", "_")
    target_dir_name = lang
    if not os.path.exists(target_dir_name):
        os.makedirs(target_dir_name)
    
    with codecs.open(f'{target_dir_name}/landing_page_{safe_lang}.html', 'w', 'utf-8') as f:
        f.write(html_out)
        
print("Successfully generated all localized landing pages!")
